### ISSUE TITLE
Is there some way of forcing peer dependencies to react-lite?

### ISSUE THREAD

**Issue by isaachinman** [Lucifier129/react-lite#66]
So, I really like this project and use it in production on several projects. One problem I run into over and over again has to do with peer deps. I'll pull an npm package into my project, eg this [React lightbox component](https://www.npmjs.com/package/react-lightbox-component), and it ends up forcing regular React to be bundled instead of react-lite due to peer deps.

Yes I could go in and change the peer deps on each package, but that defeats the purpose of a package manager. I'm using browserify by the way, but would gladly switch to webpack if it makes this easier. Is anyone aware of a good way to force peer deps?

**Comment by Lucifier129** [comment]
Suggest using webpack.

**Comment by ChieveiT** [comment]
It seems an [issue](https://github.com/npm/npm/issues/2943) of npm. Using webpack alias can help require supports alias in building but npm still install react instead of react-lite if the package has a peer dep of react. Most of time both react and react-lite will be installed in your project. Maybe you still need to work with react in development as react-lite's README suggests? BTW, I don't think npm is friendly enough to project developers, npm hopes everything is a package, which always confuses me.

**Comment by isaachinman** [comment]
@Lucifier129 Is this webpack configuration (as per the README) enough to override peer deps? If so feel free to close this.

    // webpack.config.js
    {
      resolve: {
        alias: {
          'react': 'react-lite',
            'react-dom': 'react-lite'
        }
      }
    }

**Comment by Lucifier129** [comment]
@isaachinman It will not override any deps in any package.json, just replaces react with react-lite for optimizing the script size when bundling.

**Comment by Lucifier129** [comment]
@isaachinman Yes, I think using webpack will not hit the problem that you described above.

**Comment by isaachinman** [comment]
Okay, I will begin converting my projects to webpack and let you know if I have any peer dep issues. Cheers.
